version: '3.0'

#-------------------------------------

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    expose:
      - "3306:3306"
    restart: always
    networks:
      - inception
    volumes:
      - mariadb-data:/var/lib/mysql/
    env_file: .env


  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    expose:
      - "9000:9000"
    restart: always
    networks:
      - inception
    volumes:
      - wp-data:/var/www/
    depends_on:
      - mariadb
    env_file: .env
  

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    expose:
      - "443:443"
    restart: always
    networks:
      - inception
    volumes:
      - wp-data:/var/www/
    depends_on:
      - wordpress

#-------------------------------------

networks:
  inception:
    driver: bridge
  
#-------------------------------------

volumes:
  mariadb-data:
    driver_opts:
      device: /home/seyun/data/mariadb-data
      type: none
      o: bind
  wp-data:
    dirver_opts:
      device: /home/seyun/data/wp-data
      type: none
      o: bind
