version: '3.0'

#-------------------------------------

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    expose:
      - "3306"
    restart: always
    tty: true
    networks:
      - inception
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file: .env
    
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    expose:
      - "9000"
    restart: always
    networks:
      - inception
    volumes:
      - wp-data:/var/www/html
    depends_on:
      - mariadb
    tty: true
    env_file: .env

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    restart: always
    tty: true
    networks:
      - inception
    volumes:
      - wp-data:/var/www/html
    depends_on:
      - wordpress

#-------------------------------------

networks:
  inception:
    driver: bridge
  
#-------------------------------------

volumes:
  mariadb-data:
      driver: local
      driver_opts:
        device: ${MARIADB_VOLUME}
        type: none
        o: bind
  wp-data:
      driver: local
      driver_opts:
        device: ${WORDPRESS_VOLUME}
        type: none
        o: bind
